# Generated by Django 4.1.7 on 2023-11-15 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('price_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TableB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.FloatField()),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tablea')),
            ],
        ),
    ]
